#PBS -N variant calling
#PBS -l mem=128gb
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -q biocluster-6
#PBS -j oe
#PBS -o vcf.out
#PBS -m abe
#PBS -M ggruenhagen3@gatech.edu

cd $PBS_O_WORKDIR
module purge
module load java

java -jar ../../gatk-4.0.11.0/gatk -R ../../../M_zebra_UMD2a.fasta -T HaplotypeCaller  -I ./testBamDir//testbam1.bam  -I ./testBamDir//testbam2.bam  -stand_call_conf 30 -o out.vcf -L testChunks.txt
java -jar ../../gatk-4.0.11.0/gatk -R ../../../M_zebra_UMD2a.fasta -T HaplotypeCaller  -I ./testBamDir//testbam1.bam  -I ./testBamDir//testbam2.bam  -stand_call_conf 30 -o out.vcf -XL testChunks.txt